[package]
name = "blake2b"
version = "0.1.0"
authors = ["Aki Wu <wuminzhe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9"
hex = "0.4.3"
libc = "0.2.90"

[lib]
crate-type=["dylib"]

